<a href="https://colab.research.google.com/github/ambechenwigrigoly-hub/trial/blob/main/ETL_Pipeline_Open_Meteo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

README.md


ETL Pipeline : weather

This notebook shows a ETL workflow using:

.requests to extract data from a public API
.json() to convert the API response into Python data
pandas to transform the data into a table
.to_csv() to load / save the result
.matplotlib to create simple charts

Using the public open metro API. No password or API key is needed

1. Impot of libraries: request,json,pandas and matplotlib

In [ ]:
import requests
import json
import pandas as pd
import matplotlib.pyplot as plt

2.EXTRACT: Request data from the API

Collect metro data about the weather

In [ ]:
url = "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&current=temperature_2m,wind_speed_10m&hourly=temperature_2m,relative_humidity_2m,wind_speed_10m&forecast_days=1&timezone=auto"

Parameters= {
  "current": {
    "time": "2022-01-01T15:00",
    "temperature_2m": 2.4,
    "wind_speed_10m": 11.9,
  },
  "hourly": {
    "time": ["2022-07-01T00:00","2022-07-01T01:00"],
    "wind_speed_10m": [3.16,3.02,3.3,3.14,3.2,2.95],
    "temperature_2m": [13.7,13.3,12.8,12.3,11.8],
    "relative_humidity_2m": [82,83,86,85,88,88,84,76]
  }
}

response = requests.get(url)

print(response.status_code)

200

3.Convert response to JSON data

Converting the API response into a python object i.e data_json

In [ ]:
data_json = response.json()

print(data_json)

{'latitude': 52.52, 'longitude': 13.419998, 'generationtime_ms': 0.14519691467285156, 'utc_offset_seconds': 7200, 'timezone': 'Europe/Berlin', 'timezone_abbreviation': 'GMT+2', 'elevation': 38.0, 'current_units': {'time': 'iso8601', 'interval': 'seconds', 'temperature_2m': '°C', 'wind_speed_10m': 'km/h'}, 'current': {'time': '2026-04-30T16:30', 'interval': 900, 'temperature_2m': 18.4, 'wind_speed_10m': 8.0}, 'hourly_units': {'time': 'iso8601', 'temperature_2m': '°C', 'relative_humidity_2m': '%', 'wind_speed_10m': 'km/h'}, 'hourly': {'time': ['2026-04-30T00:00', '2026-04-30T01:00', '2026-04-30T02:00', '2026-04-30T03:00', '2026-04-30T04:00', '2026-04-30T05:00', '2026-04-30T06:00', '2026-04-30T07:00', '2026-04-30T08:00', '2026-04-30T09:00', '2026-04-30T10:00', '2026-04-30T11:00', '2026-04-30T12:00', '2026-04-30T13:00', '2026-04-30T14:00', '2026-04-30T15:00', '2026-04-30T16:00', '2026-04-30T17:00', '2026-04-30T18:00', '2026-04-30T19:00', '2026-04-30T20:00', '2026-04-30T21:00', '2026-04-30T22:00', '2026-04-30T23:00'], 'temperature_2m': [8.8, 8.1, 7.4, 6.8, 6.5, 5.8, 5.3, 5.6, 7.7, 9.4, 11.2, 13.5, 15.0, 16.3, 17.5, 18.1, 18.3, 18.5, 18.5, 18.2, 17.6, 16.7, 15.5, 14.2], 'relative_humidity_2m': [47, 49, 55, 59, 58, 71, 77, 76, 57, 45, 40, 32, 34, 32, 29, 31, 32, 34, 32, 33, 34, 39, 46, 52], 'wind_speed_10m': [5.4, 5.6, 2.5, 4.1, 3.1, 1.9, 1.4, 2.0, 4.0, 4.5, 4.9, 6.0, 6.0, 6.6, 7.2, 8.8, 8.3, 8.4, 9.7, 7.3, 7.3, 5.1, 4.3, 5.8]}}

4.Create a pandas data frame

Converting the data_json to a pivot table:pandas data frame

In [ ]:
import pandas as pd

data_json = response.json()
df = pd.DataFrame(data_json['hourly'])

df.head()

               time  temperature_2m  relative_humidity_2m  wind_speed_10m
0  2026-04-30T00:00             8.8                    47             5.4
1  2026-04-30T01:00             8.1                    49             5.6
2  2026-04-30T02:00             7.4                    55             2.5
3  2026-04-30T03:00             6.8                    59             4.1
4  2026-04-30T04:00             6.5                    58             3.1

5.TRANSFORM:Rename columns

In [ ]:
df = df.rename(columns={
    "time": "ToD",
    "temperature_2m": "Temp_2m",
    "relative_humidity_2m": "RH_2m",
    "wind_speed_10m": "WS_10m"
})

df.head()

                ToD  Temp_2m  RH_2m  WS_10m
0  2026-04-30T00:00      8.8     47     5.4
1  2026-04-30T01:00      8.1     49     5.6
2  2026-04-30T02:00      7.4     55     2.5
3  2026-04-30T03:00      6.8     59     4.1
4  2026-04-30T04:00      6.5     58     3.1

6.LOAD : Save the final pandas data table as CSV file

It is the end step of the ETL

In [ ]:
df.to_csv("open_metro_data.csv", index=False)

print("CSV file saved: open_metro_data.csv")

CSV file saved: open_metro_data.csv